#import commonConfig.yml
#import ${runtime.profile}-Config.yml

entireSourcePath: "C:/Users/robin/Downloads"
musicPath: "C:/Users/robin/Music"
videoPath: "C:/Users/robin/Videos"
imagesPath: "C:/Users/robin/Pictures"
documentsPath: "C:/Users/robin/Documents"
softwarePath: "C:/Users/robin/Documents/Software"
